//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.IronLua.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neo.IronLua.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 No conversion defined from {0} to {1}. 的本地化字符串。
        /// </summary>
        internal static string rsBindConversionNotDefined {
            get {
                return ResourceManager.GetString("rsBindConversionNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No operator is defined for {1} {0} {2}. 的本地化字符串。
        /// </summary>
        internal static string rsBindOperatorNotDefined {
            get {
                return ResourceManager.GetString("rsBindOperatorNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chunk is not compiled. 的本地化字符串。
        /// </summary>
        internal static string rsChunkNotCompiled {
            get {
                return ResourceManager.GetString("rsChunkNotCompiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No type for the generic argument {0}. 的本地化字符串。
        /// </summary>
        internal static string rsClrGenericNoType {
            get {
                return ResourceManager.GetString("rsClrGenericNoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clr type expected. 的本地化字符串。
        /// </summary>
        internal static string rsClrGenericTypeExpected {
            get {
                return ResourceManager.GetString("rsClrGenericTypeExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Constant expression could not evaluate ({0}). 的本地化字符串。
        /// </summary>
        internal static string rsConstExpressionEvalError {
            get {
                return ResourceManager.GetString("rsConstExpressionEvalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Constant expression expected. 的本地化字符串。
        /// </summary>
        internal static string rsConstExpressionNeeded {
            get {
                return ResourceManager.GetString("rsConstExpressionNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Argument ar must from the same LuaThread. 的本地化字符串。
        /// </summary>
        internal static string rsCoroutineInvalidAR {
            get {
                return ResourceManager.GetString("rsCoroutineInvalidAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Argument co must be a LuaThread or a Thread. 的本地化字符串。
        /// </summary>
        internal static string rsCoroutineInvalidCO {
            get {
                return ResourceManager.GetString("rsCoroutineInvalidCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BeginResume is not called. 的本地化字符串。
        /// </summary>
        internal static string rsCoroutineNoBeginResume {
            get {
                return ResourceManager.GetString("rsCoroutineNoBeginResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yield from wrong thread. 的本地化字符串。
        /// </summary>
        internal static string rsCoroutineWrongThread {
            get {
                return ResourceManager.GetString("rsCoroutineWrongThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delegate must not have out parameters. 的本地化字符串。
        /// </summary>
        internal static string rsDelegateCouldNotHaveOut {
            get {
                return ResourceManager.GetString("rsDelegateCouldNotHaveOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expression is not enumerable. 的本地化字符串。
        /// </summary>
        internal static string rsExpressionNotEnumerable {
            get {
                return ResourceManager.GetString("rsExpressionNotEnumerable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid mode format. 的本地化字符串。
        /// </summary>
        internal static string rsFileInvalidModeFormat {
            get {
                return ResourceManager.GetString("rsFileInvalidModeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not read from file. 的本地化字符串。
        /// </summary>
        internal static string rsFileNotReadable {
            get {
                return ResourceManager.GetString("rsFileNotReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File pointer can not set to a new position. 的本地化字符串。
        /// </summary>
        internal static string rsFileNotSeekable {
            get {
                return ResourceManager.GetString("rsFileNotSeekable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not write into file. 的本地化字符串。
        /// </summary>
        internal static string rsFileNotWriteable {
            get {
                return ResourceManager.GetString("rsFileNotWriteable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not format &apos;{0}&apos; to {1}. 的本地化字符串。
        /// </summary>
        internal static string rsFormatError {
            get {
                return ResourceManager.GetString("rsFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Function &apos;{0}&apos; on type &apos;{1}&apos; already exists. 的本地化字符串。
        /// </summary>
        internal static string rsGlobalFunctionNotUnique {
            get {
                return ResourceManager.GetString("rsGlobalFunctionNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No index found for type &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string rsIndexNotFound {
            get {
                return ResourceManager.GetString("rsIndexNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type &apos;{0}&apos; is not callable. 的本地化字符串。
        /// </summary>
        internal static string rsInvokeNoDelegate {
            get {
                return ResourceManager.GetString("rsInvokeNoDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}:{1}&apos; is not readable. 的本地化字符串。
        /// </summary>
        internal static string rsMemberNotReadable {
            get {
                return ResourceManager.GetString("rsMemberNotReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}:{1}&apos; not found. 的本地化字符串。
        /// </summary>
        internal static string rsMemberNotResolved {
            get {
                return ResourceManager.GetString("rsMemberNotResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}:{1}&apos; must be unique. 的本地化字符串。
        /// </summary>
        internal static string rsMemberNotUnique {
            get {
                return ResourceManager.GetString("rsMemberNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}:{1}&apos; is not writable. 的本地化字符串。
        /// </summary>
        internal static string rsMemberNotWritable {
            get {
                return ResourceManager.GetString("rsMemberNotWritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not mix static and non-static methods ({0}). 的本地化字符串。
        /// </summary>
        internal static string rsMethodStaticMix {
            get {
                return ResourceManager.GetString("rsMethodStaticMix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not call nil value. 的本地化字符串。
        /// </summary>
        internal static string rsNilNotCallable {
            get {
                return ResourceManager.GetString("rsNilNotCallable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operator is not defined for nil-values. 的本地化字符串。
        /// </summary>
        internal static string rsNilOperatorError {
            get {
                return ResourceManager.GetString("rsNilOperatorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No length for {0}. 的本地化字符串。
        /// </summary>
        internal static string rsNoLengthOperator {
            get {
                return ResourceManager.GetString("rsNoLengthOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Object is nil. 的本地化字符串。
        /// </summary>
        internal static string rsNullReference {
            get {
                return ResourceManager.GetString("rsNullReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Number expected. 的本地化字符串。
        /// </summary>
        internal static string rsNumberExpected {
            get {
                return ResourceManager.GetString("rsNumberExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assignment expected. 的本地化字符串。
        /// </summary>
        internal static string rsParseAssignmentExpected {
            get {
                return ResourceManager.GetString("rsParseAssignmentExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The argument type must be assignable to Exception (unexpected type: {0}) 的本地化字符串。
        /// </summary>
        internal static string rsParseCatchVarTypeMustAssignableToException {
            get {
                return ResourceManager.GetString("rsParseCatchVarTypeMustAssignableToException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Number expected (&apos;{0}&apos; not converted). 的本地化字符串。
        /// </summary>
        internal static string rsParseConvertNumberError {
            get {
                return ResourceManager.GetString("rsParseConvertNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current block is closed before end of file. 的本地化字符串。
        /// </summary>
        internal static string rsParseEof {
            get {
                return ResourceManager.GetString("rsParseEof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expression has no result. 的本地化字符串。
        /// </summary>
        internal static string rsParseExpressionNoResult {
            get {
                return ResourceManager.GetString("rsParseExpressionNoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expression is not assignable. 的本地化字符串。
        /// </summary>
        internal static string rsParseExpressionNotAssignable {
            get {
                return ResourceManager.GetString("rsParseExpressionNotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Named arguments specifications must appear after all fixed arguments have been specified. 的本地化字符串。
        /// </summary>
        internal static string rsParseInvalidArgList {
            get {
                return ResourceManager.GetString("rsParseInvalidArgList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected char. 的本地化字符串。
        /// </summary>
        internal static string rsParseInvalidChar {
            get {
                return ResourceManager.GetString("rsParseInvalidChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Comment not closed. 的本地化字符串。
        /// </summary>
        internal static string rsParseInvalidComment {
            get {
                return ResourceManager.GetString("rsParseInvalidComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NewLine in string constant. 的本地化字符串。
        /// </summary>
        internal static string rsParseInvalidString {
            get {
                return ResourceManager.GetString("rsParseInvalidString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid long string delimiter. 的本地化字符串。
        /// </summary>
        internal static string rsParseInvalidStringOpening {
            get {
                return ResourceManager.GetString("rsParseInvalidStringOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No arglist defined. 的本地化字符串。
        /// </summary>
        internal static string rsParseNoArgList {
            get {
                return ResourceManager.GetString("rsParseNoArgList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It is not allowed to redefine the type. 的本地化字符串。
        /// </summary>
        internal static string rsParseTypeRedef {
            get {
                return ResourceManager.GetString("rsParseTypeRedef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected token &apos;{0}&apos;. &apos;{1}&apos; expected. 的本地化字符串。
        /// </summary>
        internal static string rsParseUnexpectedToken {
            get {
                return ResourceManager.GetString("rsParseUnexpectedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected token in Else-Statement 的本地化字符串。
        /// </summary>
        internal static string rsParseUnexpectedTokenElse {
            get {
                return ResourceManager.GetString("rsParseUnexpectedTokenElse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Literal, function or table-ctor expected. 的本地化字符串。
        /// </summary>
        internal static string rsParseUnexpectedTokenPrefix {
            get {
                return ResourceManager.GetString("rsParseUnexpectedTokenPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type &apos;{0}&apos; not found. 的本地化字符串。
        /// </summary>
        internal static string rsParseUnknownType {
            get {
                return ResourceManager.GetString("rsParseUnknownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  at  的本地化字符串。
        /// </summary>
        internal static string rsStackTraceAt {
            get {
                return ResourceManager.GetString("rsStackTraceAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  -- internal -- 的本地化字符串。
        /// </summary>
        internal static string rsStackTraceInternal {
            get {
                return ResourceManager.GetString("rsStackTraceInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  line  的本地化字符串。
        /// </summary>
        internal static string rsStackTraceLine {
            get {
                return ResourceManager.GetString("rsStackTraceLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;unknown method&gt; 的本地化字符串。
        /// </summary>
        internal static string rsStackTraceUnknownMethod {
            get {
                return ResourceManager.GetString("rsStackTraceUnknownMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is already a value with the key &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string rsTableAddDuplicate {
            get {
                return ResourceManager.GetString("rsTableAddDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to call &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string rsTableCallMemberFailed {
            get {
                return ResourceManager.GetString("rsTableCallMemberFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nil is not a valid key. 的本地化字符串。
        /// </summary>
        internal static string rsTableKeyNotNullable {
            get {
                return ResourceManager.GetString("rsTableKeyNotNullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Methods must have a LuaTable as first parameter (&apos;{0}&apos;). 的本地化字符串。
        /// </summary>
        internal static string rsTableMethodExpected {
            get {
                return ResourceManager.GetString("rsTableMethodExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operator &apos;{0}&apos; is not compatible (expected {1}). 的本地化字符串。
        /// </summary>
        internal static string rsTableOperatorIncompatible {
            get {
                return ResourceManager.GetString("rsTableOperatorIncompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operator &apos;{0}&apos; is not defined for the table. 的本地化字符串。
        /// </summary>
        internal static string rsTableOperatorNotFound {
            get {
                return ResourceManager.GetString("rsTableOperatorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recursion level is to deep. 的本地化字符串。
        /// </summary>
        internal static string rsTableRecursionLevelError {
            get {
                return ResourceManager.GetString("rsTableRecursionLevelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name for type alias is invalid &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string rsTypeAliasInvalidName {
            get {
                return ResourceManager.GetString("rsTypeAliasInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method {0}.{1} must be static, public and needs at least one parameter. 的本地化字符串。
        /// </summary>
        internal static string rsTypeExtentionInvalidMethod {
            get {
                return ResourceManager.GetString("rsTypeExtentionInvalidMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is not static. 的本地化字符串。
        /// </summary>
        internal static string rsTypeExtentionInvalidType {
            get {
                return ResourceManager.GetString("rsTypeExtentionInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; is a pointer or byref type. These types can not converted to a LuaType. 的本地化字符串。
        /// </summary>
        internal static string rsTypeInvalidType {
            get {
                return ResourceManager.GetString("rsTypeInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &quot;{0}&quot; is not supported. 的本地化字符串。
        /// </summary>
        internal static string rsTypeIsNotSupported {
            get {
                return ResourceManager.GetString("rsTypeIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid type format for &apos;{0}&apos; (unexpected: {1} at {2}; expected: {3}) 的本地化字符串。
        /// </summary>
        internal static string rsTypeParseError {
            get {
                return ResourceManager.GetString("rsTypeParseError", resourceCulture);
            }
        }
    }
}
